# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

pr: none

resources:
  - repo: self

jobs:
  - job: push_acr_for_Dev
    variables:
      - group: ACR_Valiables_For_Dev
      - name: IMAGE_NAME
        value: giikusaidevopsdemo:$(date +%Y%m%d)-$(Build.BuildId)-$(Build.SourceBranchName)

    steps:
      - script: |
          docker build -t $(SERVER)/$(IMAGE_NAME) .
          docker login -u $(ID) -p $(PASSWORD) $(SERVER)
          docker push $(SERVER)/$(IMAGE_NAME)
        displayName: Build and Push Docker image
